### ISSUE TITLE
create a socket based on a udp hostname

### ISSUE THREAD

**Issue by nickdesaulniers** [nickdesaulniers/node-rtc-peer-connection#47]
From the discussion here: https://github.com/nodejs/node-v0.x-archive/issues/5488#issuecomment-167601550

This can be a separate package.  Should see if one already exists.

**Comment by nickdesaulniers** [comment]
also, ekr recommends using dns.lookup over dns.resolve, since folks should be using the stun server url's frequently. https://nodejs.org/api/dns.html#dns_implementation_considerations

**Comment by nickdesaulniers** [comment]
not sure if we need to solve this, should go in the ice repo anyways

**Comment by Globik** [comment]
No luck for a libnice's nice_agent_send (agent, stream_id, 1, sizeof(buffer), buffer); analog in node-rtc-peer-connection?
